# Supported champions
ashe = 'Ashe.png'
missfortune = 'Miss Fortune.png'

# Client dataset
btn_ok = 'btn_ok.png'
btn_ok_bug = 'btn_ok_bug.png'
btn_close = 'btn_close.png'
btn_close_rewards = 'btn_close_rewards.png'
btn_continue = 'btn_continue.png'
btn_playagain = 'btn_playagain.png'
btn_play = 'btn_play.png'
btn_confirm = 'btn_confirm.png'
btn_findmatch = 'btn_findmatch.png'
btn_accept = 'btn_accept.png'
btn_inqueue = 'btn_inqueue.png'
btn_reconnect = 'btn_reconnect.png'
btn_lockin = 'btn_lockin.png'
btn_newrunes = 'btn_newrunes.png'
btn_editrunes = 'btn_editrunes.png'
btn_select = 'btn_select.png'
daily_play = 'daily_play.png'
daily_play_caitlyn = 'daily_play_caitlyn.png'
daily_play_ekko = 'daily_play_ekko.png'
daily_play_illaoi = 'daily_play_illaoi.png'
daily_play_thresh = 'daily_play_thresh.png'
daily_play_ziggs = 'daily_play_ziggs.png'
gamemode_training = 'gamemode_training.png'
gamemode_coopvsai = 'gamemode_coopvsai.png'
gamemode_pvp = 'gamemode_pvp.png'
map_aram = 'map_aram.png'
map_summonersrift = 'map_summonersrift.png'
queue_intro = 'queue_intro.png'
queue_beginner = 'queue_beginner.png'
queue_intermediate = 'queue_intermediate.png'
summonerspell_heal = 'summoner_heal.png'
summonerspell_ghost = 'summoner_ghost.png'
summonerspell_barrier = 'summoner_barrier.png'
summonerspell_teleport = 'summoner_tp.png'
summonerspell_exhaust = 'summoner_exhaust.png'
summonerspell_cleanse = 'summoner_cleanse.png'
summonerspell_ignite = 'summoner_ignite.png'
summonerspell_flash = 'summoner_flash.png'
honor_a_teammate = 'honor_a_teammate.png'
daily_play = 'daily_play.png'
pick_your_champion = 'pick_your_champion.png'

# Game dataset
healthbar_turret = 'healthbar_turret.png'
healthbar_enemy = 'healthbar_enemy.png'
healthbar_minion = 'healthbar_minion.png'
healthbar_ally = 'healthbar_ally.png' # Not in use
interface_settings = 'interface_settings.png'
interface_cam = 'interface_cam.PNG'
interface_death = 'interface_death.png'
interface_low_hp = 'interface_low_hp.png'
interface_heal = 'interface_heal.png'

# Specific
btn_ok_gpu = 'btn_ok_gpu.png'
